### ISSUE TITLE
[class 1] 오늘 강의 끝나고 궁금한 것들 여기에 올려주세요

### ISSUE THREAD

**Issue by ozt88** [ozt88/C-PL#2]

**Comment by kimsin3003** [comment]
구조체 네임스페이스 클래스 모두 비슷한 기능인 것 같은데 세가지나 있는 이유가 뭔가요...?
각자 대체 불가한 기능들을 가지고 있는건가요?
클래스가 다른걸 다 포함 할 것 같아서..

**Comment by helloheesu** [comment]
- 깃헙 사용팁 알려주세요 (깃 자체 말고 플러그인이나 소스트리 등 응용 프로그램)
  - 2013년 3학기에는 [이 글](http://www.sysnet.pe.kr/2/0/1501)에서 나오는 것처럼 tortoise 라는 걸 썼는데, VS에서는 물론이고 윈도우 탐색기에서도 바로 깃 제어하기가 편해서 꽤 좋았어요. 근데 설정 어떻게 하는지 까먹음. 꽤 귀찮아 보임.
  - [깃헙익스텐션 for VS](https://visualstudio.github.com/)가 있네요. 는 깃헙GUI 익스텐션일뿐이라서 소스트리로 하하하하
- 비주얼 어시스트 맛 보기 시연 부탁드립니다

**Comment by atgchan** [comment]
비주얼 스튜디오 좋은 컬러스킨 추천해주세요

**Comment by helloheesu** [comment]
- 프로젝트 와 솔루션의 차이가 뭔가요 
- 헤더파일이라는 폴더?? 는 뭔가요

**Comment by FeatherHub** [comment]
> 1< : C++에서 변수는사용하기 직전에 선언하는 게 효율적인 이유가 뭔가요?
> 
> 2< : 컴퓨터에서 난수를 생성하는 원리는 어떻게 되나요?
> 
> 3< : 깃허브에서 줄의 맨 앞에  '>'를 쓰면 왜 보이지 않을까요?
