### ISSUE TITLE
[Class 2] 플립러닝 보고 궁금한거나 아무거나 질문해주세요

### ISSUE THREAD

**Issue by ozt88** [ozt88/C-PL#3]
http://cafe.nhnnext.org/index.php?vid=plincpp2014&mid=materials&page=3&document_srl=178029
http://cafe.nhnnext.org/index.php?vid=plincpp2014&mid=materials&page=3&document_srl=178066
http://cafe.nhnnext.org/index.php?vid=plincpp2014&mid=materials&page=3&document_srl=178069
http://cafe.nhnnext.org/index.php?vid=plincpp2014&mid=materials&page=3&document_srl=178894
http://cafe.nhnnext.org/index.php?vid=plincpp2014&mid=materials&page=3&document_srl=178898

**Comment by hataeho1** [comment]
178066 동영상 강의를 보면
3분 40초 쯤에 szText라는 변수를 선언하는데
sz는 무엇의 약자인지 궁금합니다.

``` c
char* szText = "Hello World3!\n";
printf_s("%s", szText);
```

**Comment by ozt88** [comment]
stringZero 널로끝나는 문자열이란 뜻입니다.
