### ISSUE TITLE
[Class 2] 수업 끝나고 숙제/플립러닝 공지

### ISSUE THREAD

**Issue by ozt88** [ozt88/C-PL#4]
플립러닝 미리보기 : 플립러닝 3 string ~ 플립러닝 4 접근제한자  
링크 : http://cafe.nhnnext.org/index.php?vid=plincpp2014&mid=materials&page=2    

오늘 강의자료 : https://www.slideshare.net/agebreak/pl-in-c-5  
숙제 : BattleShip게임에 필요한 객체들의 인터페이스를 구현하세요

**Comment by kimsin3003** [comment]
상속받은 클래스에서 부모 클래스의 변수에 접근해서 변경할 때, 부모클래스 변수 내용도 바뀌나요?
